### ISSUE TITLE
Evolution of gen_twirpjs

### ISSUE THREAD

**Issue by sw-clough** [gnarbox/twirpjs#2]
I'm just wondering why gen_twirpjs subpackage has evolved the way it has? I actually prefer version 0.0.5 for my project. It seems in later/current version, you have made some react code a dependency, and I don't see the reason for this. It seems sensible for the generated code to not use any external packages besides the essential twirpjs package and the generated protobuf-js file.

**Comment by fritzherald** [comment]
Hi @sw-clough,

Because streaming endpoints are no longer on the roadmap for the main twirp repository, this project is no longer being actively maintained or developed. I've added a deprecation notice to the main readme and it links to an issue on the twirp repo where you can read more about the reasoning behind not adopting streaming support for twirps. If you're not using streaming endpoints, the twirp repo links to a couple other JavaScript twirp implementations that may be closer to what you're looking for. If streaming is part of your requirements, then at this point the best option is probably to chose an rpc framework that explicitly supports streaming (e.g. gRPC).

**Comment by sw-clough** [comment]
No worries. Streaming is not a requirement for me, and gRPC seems difficult to use in the browser, hence Twirp is ideal. I started using this package because it uses protobuf.js, instead of the google generator. I did test some of those other options, but didn't like various aspects of them, and settled on this one. I guess I will go back and review those other options, and/or fork this package and maintain it. Thanks.
